-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 19:37:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Armazem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Armazem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Armazem` DEFAULT CHARACTER SET utf8 ;
USE `Armazem` ;

-- -----------------------------------------------------
-- Table `Armazem`.`Gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Gestor` (
  `codID` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Palete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Palete` (
  `codID` VARCHAR(5) NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  `refrigerado` TINYINT NOT NULL,
  `LocalizaçaoX` INT NULL,
  `LocalizaçaoY` INT NULL,
  PRIMARY KEY (`codID`, `conteudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Robots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Robots` (
  `codID` VARCHAR(5) NOT NULL,
  `ordens_feitas` INT ZEROFILL NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Requisicao` (
  `codID` VARCHAR(5) NOT NULL,
  `conteudo` VARCHAR(90) NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Armazem`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Armazem`.`Entrega` (
  `codID` VARCHAR(5) NOT NULL,
  `palete` VARCHAR(5) NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
